### ISSUE TITLE
kaggle credential in the notebooks

### ISSUE THREAD

**Issue by yerramasu** [vbookshelf/Mammogram-Mass-Analyzer#2]
Dear author,

I think you might have accidentally committed your kaggle credentials in the notebooks

Regards

**Comment by vbookshelf** [comment]
Hi @yerramasu. Thank you for taking the time to warn me about this. Actually I was careful to expire the API token before making the notebooks public. Therefore, it can't be used to access my Kaggle account.
Thanks again.
